import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/glocktopus.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Eyebrows.geometry}
                material={materials["Material.003"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={materials["Material.001"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus_1.geometry}
                material={materials["Material.006"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mouth.geometry}
                material={materials["Material.005"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Eyes.geometry}
                material={materials["Material.002"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Floor.geometry}
                material={materials["Material.008"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Icosphere.geometry}
                material={materials["Material.004"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Icosphere_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5001.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5001_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5001_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5002.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5002_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5002_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5003.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5003_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5003_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5004.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5004_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5004_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5005.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5005_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5005_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5006.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5006_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5006_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5007.geometry}
                material={materials.Metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5007_1.geometry}
                material={materials.Black}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pistol_5007_2.geometry}
                material={materials.LightMetal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002.geometry}
                material={materials["Material.010"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002_1.geometry}
            // material={materials.Outline}
            >
                <meshBasicMaterial color="black" />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002_2.geometry}
                material={materials["Material.012"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Node-Mesh"].geometry}
                material={materials.mat23}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Node-Mesh_1"].geometry}
                material={materials.mat14}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials["Material.013"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Text001.geometry}
                material={materials["Material.011"]}
            />
        </group>
    );
}

useGLTF.preload("/glocktopus.glb");
